### ISSUE TITLE
Show how many likes/thanks a post got since the last visit

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#153]
link: https://community.mybb.com/thread-169382-post-1288075.html#pid1288075

> Could it be made more dynamic; instead of alerting who has liked/thanked a post, instead alert how many likes/thanks a post has got since the last alert

I.e. Your post "RE: XYZ" has got a new like / Your post "RE: XYZ" has got 5 likes

Would that not avoid the limitations, but provide a bit more information to members?

I think most aren't too bothered about who has liked a post (and can see that in the post) but like to know which one of their posts is gaining recognition

**Comment by Eldenroot** [comment]
@lairdshaw you had some suggestion for this, is it still doable or not (MyAlert limitation)? Let us know, thanks

**Comment by lairdshaw** [comment]
@Eldenroot, I have reviewed our private conversation about this. First, though, I think that it is important to clarify the essence of this issue, which, as I see it, is this: if more than one person "likes" a post in between the "liked" person checking alerts, only the first person's "like" will show up in the alerts. That other people have also liked the post, let alone who those people are, will be missing information.

In our private conversation, I suggested three possible ways to fix this problem, which I will quote verbatim as they are, in my opinion, still valid:

1. Get a new alert every time somebody likes one of your posts, regardless of any existing alerts (NoAdmin's original request).
2. Get a single alert for each post that has been liked since the last like alert (if any) for that post was read: this alert would say something like "[n] new likes for your post, from [member X] and [n-1] other members" (roughly what ended up being requested in the ticket - similar to Facebook as you suggest).
3. As above but show not a count of new likes and the first new liker: instead, name ALL new likers (perhaps with a character limit). This would be like the existing functionality except that it would update as new users like the post.

In our private conversation, I suggested that we could implement all three options and allow each user to choose which one they wanted via a setting in the UCP under Alerts -> Alert Settings, however, I noted that there's no way to hook into the function that manages the display and saving of those settings. I added that I suppose we could add it elsewhere in the UCP, but then it might be difficult to find and confusing given its separation from the Alerts menus.

We briefly canvassed the possibility of creating a pull request to the MyAlerts repository to add such a hook, though we noted that the repository is not very active - though Eaun *has* merged some pull requests that I submitted a while back, so we know that he is open to them.

**Comment by Eldenroot** [comment]
Thank you for your detailed summary. I remember out conversation... I agree with you, I like ACP option for that bit this will need some changes in MyAlerts too.

Do you wanna work on this or leave it when MyAlert will include support for this?

**Comment by lairdshaw** [comment]
Well, in hindsight, it might be unnecessary to provide three options. Maybe we could simply pick *one* of those options, which we think is best in general, and implement that. That way we don't need to submit any pull requests for MyAlerts, and the implementation in general is simpler. What do you think?

**Comment by Eldenroot** [comment]
We should provide option no. 2.

I think that no. 1 would be annoying in bigger boards, no. 3 is not bad but likes/thx count is not included, would be difficult to listen all likers.

What do you think?

And what about @effone or @WildcardSearch feedback?

**Comment by WildcardSearch** [comment]
What is current behavior, @Eldenroot? (User gets one alert per like? User gets an alert for first like, but nothing for subsequent likes?)

If it works like the rest of MyAlerts, you would just get `xxx liked your post, there may be other new likes as well`...

Help me see what behavior is and I'll be glad to chime in with an opinion.

**Comment by Eldenroot** [comment]
Now it displays only one time

**Comment by WildcardSearch** [comment]
Then, I would say you need to send a single alert for every user that likes the post — just like reputation points.

**Comment by Eldenroot** [comment]
We are limited by MyAlerts, maybe we should reconsider when MyBB will have inbuild notification system in core.

What do you think @lairdshaw

**Comment by lairdshaw** [comment]
I still like the idea (number 2). As you say though, we are limited by MyAlerts - I'm not sure how feasible it is to hook into it to implement this feature. Maybe I'll take a dig around in the code and investigate and get back to you later. I might be able to come up with a proof of concept. If not, let's as you say wait until MyBB has inbuilt notifications.

**Comment by Eldenroot** [comment]
OK, I agree!

**Comment by Eldenroot** [comment]
Added via https://github.com/mybbgroup/Thank-you-like-system/pull/263 thx @lairdshaw
