### ISSUE TITLE
SQL error: 1054 - Unknown column 'tyl_tnumtyls' in 'field list'

### ISSUE THREAD

**Issue by piratesgg** [mybbgroup/Thank-you-like-system#237]
I checked phpMyAdmin and i'm not sure what to do?

**SQL Error:**
1054 - Unknown column 'tyl_tnumtyls' in 'field list'
**Query:**
UPDATE mybb_threads SET tyl_tnumtyls=tyl_tnumtyls+1 WHERE tid='173'

**Comment by lairdshaw** [comment]
That column was dropped in version 3.1.0. My guess is that you upgraded the plugin - which caused the column to be dropped - and then copied the plugin's files from an earlier version without properly reinstalling it.

My suggestion is to simply upgrade to the latest version of the plugin by following the instructions in README.md.

**Comment by lairdshaw** [comment]
Any feedback on this issue? If not, I'll close it.

**Comment by lairdshaw** [comment]
Closing this. Please feel free to reopen as necessary.

**Comment by lairdshaw** [comment]
A belated note: it could be that this issue is/was due not to downgrading the plugin without proper reinstallation, but due to another plugin (such as, in the linked-to thread, the Hide Content plugin) relying on this field which as been dropped. For more info, see this thread:

https://community.mybb.com/thread-228028-post-1350667.html
