### ISSUE TITLE
Refresh page when click add Like

### ISSUE THREAD

**Issue by TessiXakaT6** [mybbgroup/Thank-you-like-system#238]
Hey, I wanted to know how to make sure that when someone clicks on the button to add a like it refreshes the web page.

**Comment by lairdshaw** [comment]
That should already be happening automatically. If not, you might need to debug why - check the Javascript console in your browser, for example, by pressing F12 before adding/removing likes, and share with us any errors that occur when you add/remove a like.

**Comment by TessiXakaT6** [comment]
There is no javascript error when I press the like button but no page resfresh is performed

For the like counter to update I have to do F5.

**Comment by lairdshaw** [comment]
The like counts for posts don't update by design, but the list of "likers" in the footer of the post should update by AJAX - those following the text "The following [n] user[s] like [username's] post".

A full-page reload is currently only performed when Javascript is disabled. If you want it to occur even when Javascript is enabled, then probably you should edit the `thankyoulike_button_add` and `thankyoulike_button_del` templates to remove the `onclick` attribute of each link.

**Comment by TessiXakaT6** [comment]
Ok so in my add button for like i have this : 

`<a style="background: #50505099;" class="add_tyl_button" href="thankyoulike.php?action=add&amp;pid=13&amp;my_post_key=0fa1886ecb5f22996dc67ee7c71d3c2e" onclick="thankyoulike.add(13, 7); return false;" title="Like this Post" id="tyl_btn_13"><span style="color: green;" id="tyl_i13"><i style="color: green;" class="fa fa-heart fa-fw"></i> `Like</span></a>`

Should I remove the onClick attribute so that the page refreshes completely when the button is clicked?

**Comment by lairdshaw** [comment]
Yes, since you want a full-page refresh. You should do this in the Admin Control Panel (ACP) under "Templates & Style" -> "Templates". And if you want the same effect on unliking a post, you should do it for the remove button too.

**Comment by TessiXakaT6** [comment]
Oh, yes, it works perfectly, thank you. The remove likes button is desactivated so it's good ^^

**Comment by lairdshaw** [comment]
You're welcome. Glad you got the outcome you wanted.
