### ISSUE TITLE
List of thank you/likes with basic statistics (based on MyBB reputation feature)

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#244]
This was discussed earlier¨- more info here

https://github.com/mybbgroup/Thank-you-like-system/issues/242#issuecomment-700686691

**Comment by Eldenroot** [comment]
@lairdshaw - lets discuss this one :) I think this would be a great addition to this TYL system ;)

**Comment by lairdshaw** [comment]
OK. My suggestion is that we use a display pretty much like the reputation display that you used as an example, although obviously it would be a lot simpler, because there are no such things as "neutral" or "negative" tyls, and there is no such distinction as tyls from members and tyls from posts.

I also suggest re permissions that we simply honour the per-usergroup "Can view user profiles?" setting (in the "Forums and Posts" tab).

Your thoughts?

**Comment by lairdshaw** [comment]
(I'm undecided as to whether we should have a list of likes below the summary as there is a list below the reputation summary - perhaps the "Find all threads tyled" and "Find all posts tyled" are sufficient?)

**Comment by lairdshaw** [comment]
(In which case, we could make the summary a simple pop-up box, falling back to full-page if Javascript is not enabled.)

**Comment by Eldenroot** [comment]
OK, that makes sense!

**My ideas:**
- display not only these 4 "time periods" but use these: last week, last month, last 3 months, last 6 month, last 12 month, all time (or do we need more options?)
- display 3/ users who given the most amount of thx/likes (who liked/thanked) most times to the user's posts
- we can display as a new table in member profile below the "most thanked/liked post"
- about permissions - good idea
- list of thanks/likes - maybe we can just add a simple list with the latest 20 received likes/thanks and then "load more" which will redirect you to the "Find all posts liked" page? This needs to be discussed, because it will depend how we wanna display the content, as a table or as a new page? Maybe it will make more complicated and only find all thanked post would be enough... I dont know

**Comment by lairdshaw** [comment]
Happy with all of that. Re table in profile versus new page: yes, it will depend on whether we add a listing of likes. In favour of that listing is that it provides info not provided by the "Find all posts liked" results: likes in descending order of date received. Against the idea of that listing is that, as you say, it complicates the plugin.

My overall assessment: let's err on the side of providing too much information rather than too little, even if it does complicate the plugin. In that case, we'd use a new page for this feature. The problem then is how to clue members in to the fact that the page exists. Would it be sufficient just to provide a link in the profile from the number beside "Total tyls received"?

Also, would we want a similar page for tyls _given_?

**Comment by Eldenroot** [comment]
@lairdshaw 

Maybe a table would be enough, place it in a member profile page.

For received/given... can we just put both together? We can use same design as reputation, but instead of "neutral" column we can add received, and next to it given.

**Comment by lairdshaw** [comment]
See what you think of this, @Eldenroot.
