### ISSUE TITLE
We should not re-add template insertion on deactivate and activate of plugin 

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#302]
When you deactivate the plugin, all settings and template changes are saved and not lost.

When you activate again, all is restored except the template additions - they are "reset" and readded to their locations based on our activate procedure.

We should not do this in my opinion.

**Comment by lairdshaw** [comment]
Activating the plugin should only (re)create templates when also installing or upgrading the plugin. Deactivating and then reactivating the plugin without uploading a new version in between should have no effect on the templates.

And even on upgrade (triggered by activation of a new version of the plugin), only the plugin's master templates should be recreated - those with an `sid` of -2. Non-master plugin templates (those edited by the user) should, after the activation-triggered upgrade, show up in Find Updated Templates if they were edited by an admin since last changed in the plugin, but they should otherwise not be modified.

That's at least the intended behaviour of the current code. So, here are two questions:

1. Are you finding the actual plugin behaviour to differ from that intended behaviour?
2. Do you think in any case that that intended behaviour should be different?

**Comment by Eldenroot** [comment]
I am not sure what the issue is, but lets me conclude:

- when I deactivated the TYL system and activate it again (same version) -> all templates changed made by me was restored, so I didnt lose anything. However the template insertions (to postbit_classic, member profile etc) were deleted (I moved them to different part of templates for customization) and added again to their "original" places how we do during installation process. So I have to manually move them to desired places again. Not a big deal but quite annoying to do that after every update od deactivation.

**Comment by lairdshaw** [comment]
Oh, I see now. You're talking about the changes to core templates made using the `find_replace_templatesets()` function, not the new templates added by the plugin.

It seems to be standard practice to make/undo these changes in a plugin's activate/deactivate functions. When a plugin is deactivated, there shouldn't be any trace of it remaining in core templates (otherwise it's still in a sense "partially active"). I'm not sure how to get around this problem. Do you have any suggestions?

**Comment by Eldenroot** [comment]
@lairdshaw - I am sorry, I didnt see this reply. 

I am not sure, maybe add some kind of upgrade script or update?

**Comment by lairdshaw** [comment]
You mean, so there is no need to deactivate-reactivate to upgrade? So, the upgrade procedure might be something like: copy new files over old ones, then go to the ACP Plugins page and click an "Upgrade" button beside the plugin?

That's a very nice idea.

The only problem I can see (and it's a minor one) is that in between copying new files and clicking the "Upgrade" button, the plugin would potentially be in an inconsistent state, since there might be database changes that need to be made in the upgrade which the newly copied files rely on. We can easily deal with that problem though by instructing admins to disable the plugin via its settings page before upgrading, and re-enable it afterwards.

**Comment by Eldenroot** [comment]
I just dont like template changes which are redone... this could be a potential issue for many admins because they do not want to lost their modifications etc. we should bring easy upgrade process if it is somehow possible and not time hungry :)

**Comment by Eldenroot** [comment]
Friends @SvePu and @lairdshaw - this one needs some discussion. I got many PMs from users - nobody likes to readd all template changes after upgrade (including me hehe :) )

**Comment by lairdshaw** [comment]
A simple way to achieve what you want is to add a plugin setting something like: "Do not make changes to core templates on activation/deactivation", by default toggled off. It would take only a few lines of code. What do you think?

**Comment by Eldenroot** [comment]
I am not sure, but I think that this plugin https://community.mybb.com/mods.php?action=view&pid=191

Works like you described.

There is a notice displayed on plugin page to run the update and apply template changes. You can run or ignore. 

Feel free to open the PR :)

Thank you

**Comment by lairdshaw** [comment]
I had a close look at that plugin. Its upgrade process is generally nicely done, however, I remain of the opinion that moving the "add/remove changes to core templates" routines out of (de)activation and into (un)install is bad practice, firstly for [the reason I shared above](https://github.com/mybbgroup/Thank-you-like-system/issues/302#issuecomment-761597764), and secondly - more pragmatically - if plugins are deactivated without template changes being reverted, then PHP 8 will emit warnings on rendering those templates where the changes include variables (because those variables will be unset because the plugin is inactive).

This is not a big deal if the plugin is only to be temporarily deactivated so as to trigger an upgrade routine on reactivation after copying new files across, which is why I continue to think that the plugin setting I suggested above is the best approach. It's also the simplest and most straightforward approach. That's just my two cents though. Others might differ.

**Comment by Eldenroot** [comment]
OK buddy, your solution is better ;)
