### ISSUE TITLE
MyBB 1.8.28+ incompatibility - member profile - post meesage is parsed incorrectly

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Thank-you-like-system#319]
![image](https://user-images.githubusercontent.com/778890/143306022-39c03631-abd1-4ccf-974b-ae9b56efa21b.png)

`[size=medium][font=Calibri,sans-serif]`

@lairdshaw - please could you fix this one? I think that 1.8.28 breaks this.

**Comment by lairdshaw** [comment]
I doubt that this issue has anything to do with MyBB core or core version, but perhaps I'm mistaken. It seems to be caused by the "Trophy post character cut-off" setting being set to a value other than zero, such that for this particular trophy post, the closing tags for [size] and [font] are cut off, meaning that the parser then renders the opening tags as-is, since it can't parse them.

The fix would probably best be handled - if at all - in core, rather than in this plugin: a sort of "auto-insert any missing closing MyCode tags prior to rendering" feature. That's probably not such an easy feature to implement though.

**Comment by Eldenroot** [comment]
OK, thank you for your feedback!

**Comment by Eldenroot** [comment]
So this is a mybb core related?

**Comment by lairdshaw** [comment]
It's a general problem that if we cut off closing tags, the parser doesn't render the message _as if_ those closing tags were there - instead, it renders the opening tags as plain text. We _could_ try to fix this ourselves, but better would be a solution in core which would reusable for others. Perhaps an alternative solution is rendering the message to plain text rather than to HTML. IIRC, that that's how message fragments are rendered in search results.

**Comment by SvePu** [comment]
Maybe disallowing parser option mycode by default an parsing the message before cutting.

**Comment by Eldenroot** [comment]
@SvePu this idea is good, we can just display text, we do not need any formating of text here. It is just a part of text. Could you please make a PR?

**Comment by SvePu** [comment]
@Eldenroot Please check the modification

**Comment by Eldenroot** [comment]
@SvePu - I would like to, but if I update to the latest version I will have to redo all my template modifications - see https://github.com/mybbgroup/Thank-you-like-system/issues/302

I am going to install a test board for this, need some time.

Thank you!

**Comment by SvePu** [comment]
@Eldenroot for testing you dont need to reinstall ... just replace plugin files on server.

**Comment by Eldenroot** [comment]
Closing as complete.
